### ISSUE TITLE
Version gem not found

### ISSUE THREAD

**Issue by ream88** [RyanScottLewis/jqtree-rails#5]
Latest push caused an issue for me:

```
There was a LoadError while evaluating jqtree-rails.gemspec: 
cannot load such file -- version from
  /Users/mario/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/bundler/gems/jqtree-rails-edd3c7f36750/jqtree-rails.gemspec:2:in `<main>'

Does it try to require a relative path? That's been removed in Ruby 1.9.%   
```

**Comment by RyanScottLewis** [comment]
`bundle install`

**Comment by ream88** [comment]
I called `bundle update`...

**Comment by RyanScottLewis** [comment]
Just `gem install version` then `bundle install` I suppose.

**Comment by ream88** [comment]
Did not fix it. Maybe it's because Gemfile.lock is included in the repo.

**Comment by RyanScottLewis** [comment]
Well the Gemfile is using the gemspec to find the gem dependencies.. but the version in the gemspec is being set by the VERSION constant.. which is now being set by the version gem. Catch 22.

Remove the `gemspec` line from the Gemfile and add the dependencies to it. then `bundle install`.
